### PR TITLE
Fix https://github.com/jenkinsci/openstack-cloud-plugin/issues/189

### PR DESCRIPTION
**Pull request by Chekov2k**
https://github.com/jenkinsci/openstack-cloud-plugin/issues/189

### CODE REVIEW

**Comment by olivergondza** [comment]
Does this fix the _Test Connection_ functionality only or the rest works as well? Are you able to provision machines with this fix?

---

My point is, if the plugin is incompatible and can not work with this version of neutron at all, it is actually better it fails aloud this soon. But if this is the only place where we hit the incompatibility, you fix will be worth merging,

**Comment by Chekov2k** [comment]
Sorry Oliver, should have mentioned that as far as I can tell, all the functionality of the plugin is working. I can select images, flavours, networks, etc. and also can spin up on demand slaves

**Comment by olivergondza** [comment]
Merged, thanks!

**Comment by Chekov2k** [comment]
Thank you!

**Pull request merged**
