### PR TITLE
Replace JClouds with Openstack4j

### PR DESCRIPTION
**Pull request by olivergondza**
@mavlyutov, I started experimenting with openstack4j basing the effort on jclouds 1.9 effort to take advantage of singlemodule project.

Marat, I would like you to look at following thing: There do not seem to be a way to list *configured regions* using openstack4j. What does it do actually? Can you point it to correct region using different keystone api url? For now, I have removed that completely but it will be possible to add it back (without the available region completion).

Todo:

- [x] Blob store support: ~~Bring it back or~~ remove it
- [x] Credential injection removed - the logic belong to configuration management
- [x] Slaves hang around in jenkins and openstack forever after restart.

### CODE REVIEW

**Comment by mavlyutov** [comment]
Hi! 
I looked at o4j about year ago and it was pretty green. Let's see what's for now.
Let me a few days to try it. But I like the main idea - to get rid of monstrous jclouds and use smth neat and singlemodule.

As for regions - we have really big openstack system with http-balancer atop of keystone. And our devops team kindly asks using that balancer instead of direct region-based keystone urls. So yes, we need it, with listing or without it.

**Comment by olivergondza** [comment]
@mavlyutov, thanks. Can you have a look on ee38148 and 6b579b1, the feature seems to be removed some time ago.

**Comment by olivergondza** [comment]
Btw, are there any users of blobstore?

**Comment by mavlyutov** [comment]
>Btw, are there any users of blobstore?
not me

**Comment by pupssman** [comment]
github says "This branch is up-to-date with the base branch", but jenkins build fails with error of automatic merging. Why is that?

**Comment by olivergondza** [comment]
@pupssman, this PR contains the refactorization from miltimodule to singlemodule maven project that does not merge cleanly back to master. To merge this PR I will use "our merge" (throw away all the changes on the master and pretend it is merged) that would require to go through all recent changes on master and cherry-pick it here so it will merge cleanly as safely (IOW, it should be me who is responsible to make sure this is mergeble, not the maintainer). The build fails because of one conflicting file as my master was outdated when I oursmerged.

Fixed: https://jenkins.ci.cloudbees.com/job/plugins/job/openstack-cloud-plugin/87/console

**Comment by pupssman** [comment]
Oh, nice! Keep up the good job)

**Comment by olivergondza** [comment]
There seems to be a limitation of openstack4j as it is not able to set ssh/pwd credentials (jclouds executes scripts over ssh to get the job done). Running [ATH](https://github.com/jenkinsci/acceptance-test-harness/blob/master/src/test/java/plugins/OpenstackCloudPluginTest.java) against 1.8 it seems, it never actually created user accounts but perhaps it is able to populate those accounts with credentials.

As users usually want both, the logic has to be separated between cloud-init creating the account and a plugin populating it with credentials. I understand this is a breaking change for some deployments, but how about making all this a responsibility of cloud-init (openstack populates default account with key identified by `key-name`)? We do not have to rely on fragile shell scripts messing with the system and it will help us getting closer to windows support. WDYT?

**Comment by olivergondza** [comment]
I have deployed this to production and it seems to be working fine. I will go through the commits that landed in master since this branch was forked and cherry-pick them here.

As this is quite complex change, I would like to release this as 2.0(-beta).

**Comment by olivergondza** [comment]
Finally, 2.0 beta is out (should be in experimental update center in a minute): http://maven.jenkins-ci.org:8081/content/repositories/releases/org/jenkins-ci/plugins/openstack-cloud/2.0-beta/

@mavlyutov, @pupssman, can you give it a try?

**Comment by imduffy15** [comment]
Thanks for your work on this @olivergondza it works nicely. Would be awesome to see support for V3 keystone with domains.

**Pull request merged**
