### PR TITLE
[JENKINS-65157] Render div based UI for new Jenkins cores

### PR DESCRIPTION
**Pull request by olivergondza**
Introduce a shim to choose the wrapper dynamically.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

https://issues.jenkins.io/browse/JENKINS-65157

### CODE REVIEW

**Comment by kofemann** [comment]
Thanks for fixing this issue. How can I build and test it on the local system?

**Comment by olivergondza** [comment]
@kofemann, thanks for volunteering to do that. `mvn clean package` will build a hpi to deploy, `mvn clean hpi:run` will run a test instance for you.

**Comment by kofemann** [comment]
Works for me, thanks!

**Comment by ondrejbudai** [comment]
Works for me well, thanks!

**Pull request merged**
