### PR TITLE
Fix #77: Load all images from glance 2

### LINKED ISSUE #77: Plugin doesn't respect glance API version
Current Glance API version is 2. So in service catalog we have endpoint to image-service in format "HOST/v2". When plugin trying to get list of available images, it send request "GET /v2/images/detail". However, in v2 API there is no target "/images/detail", and so list of images not loaded.

Please, fix plugin to force use v1 API. Or implement v2 support.

> Jenkins 1.651
> Plugin 2.6

Thanks.

### PR DESCRIPTION
**Pull request by olivergondza**
The openstack4j does not implement pagination for glance 2 so it needs to be done explicitly.

### CODE REVIEW

**Comment by olivergondza** [comment]
Yeah, that openstack4j dependency is not public due to the stale state of the library. I prefer to control the explicit library version than just use `-SNAPSHOT`.

**Comment by olivergondza** [comment]
I have deployed this hotfix internally and provided it will work correctly until tomorrow, I will release this.

**Comment by guilhermesteinmuller** [comment]
I really appreciate it @olivergondza .

Let me know if you need something.

Best regards.

**Comment by maggosourabh** [comment]
Hello @olivergondza 

Hope it is still not live as i can see some check failed in last merge.

**Comment by olivergondza** [comment]
@maggosourabh, the only failure I got is the one from building with unreleased dependency. Do you have some other problem in mind?

**Comment by maggosourabh** [comment]
@olivergondza Thank you.

Let me fetch the new code and see if it works for me.

**Pull request merged**
