### PR TITLE
Fix javadoc issues

### PR DESCRIPTION
**Pull request by pjanouse**

### CODE REVIEW

**Comment by olivergondza** [comment]
I hate how javadoc forces people to specify all these. Frankly, I see no value in these whatsoever: "Get all Openstack computers. / @return List of openstack computers." - it is nothing one would not grok from the signature `public static @Nonnull List<JCloudsComputer> JCloudsComputer#getAll()`.

Is there a way to prevent javadoc from complaining about missing method javadoc directives? I only ever got as far as preventing it to fail the build...

**Comment by pjanouse** [comment]
Well, if we want to do that (global only), we can put following into pom.xml:

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <configuration>
                        <additionalJOption>-Xdoclint:-missing</additionalJOption>
                    </configuration>
                </plugin>

**Comment by olivergondza** [comment]
Yeah, let's do that. Btw, I have just checked missing doctags is the only thing it ever complains about. Not parsable file, illegal doctags, broken javadoc syntax, `@link` to types that does not exist, broken html tags - none of that is reported as a problem. :confused:

I suspect we have it misconfigured. perhaps in parent-pom?

**Comment by pjdarton** [comment]
Personally, I'm a big fan of Javadoc - and I love having the IDE display Javadoc information when you mouse-over a method call - but I agree that it is unnecessary for methods that are simply so obvious that they don't need any documentation.

If we can figure out a way of configuring the maven plugin not to worry about trivial methods missing documentation (but to insist that any documentation that is present is well-formed) then I may make equivalent changes to the vsphere and docker plugins too ;-)

**Comment by pjanouse** [comment]
Based on discussion with Oliver, this looks the best option we have in our hands...

**Comment by pjanouse** [comment]
@olivergondza 
I hope found a portable solution finally, version 3.0.0 and above is needed for this to be working properly.

This setting left all checks applied but missing are switched off.

**Comment by pjdarton** [comment]
Awesome - I might steal that and put that config into the vSphere plugin :grin:

**Pull request merged**
