### PR TITLE
Add retry loop to Launcher

### PR DESCRIPTION
**Pull request by zxiiro**
Sometimes we can get an authentication error while trying to login to a
new node if connecting too quickly. Our systems do not create a jenkins
user account until the system has been fully commissioned so it could
take a 10s of seconds before authetication is possible.

This commit adds a retry loop to the launcher so that we do not assume
the system is not available.

I'm not sure how to make this accept parameters but the current code
hardcodes a 3 minute timeout before giving up.

### CODE REVIEW

**Comment by olivergondza** [comment]
> I'm not sure how to make this accept parameters but the current code
hardcodes a 3 minute timeout before giving up.

The timeout is already in `SlaveOptions` associated with computer.

**Comment by zxiiro** [comment]
SlaveOptions is only available for JCloudsSlaves but I'm not sure if I can class cast it back. I tried doing this:

```
        JCloudsSlave jcloudsSlave = (JCloudsSlave) computer;
        Integer launchTimeout = jcloudsSlave.getSlaveOptions().getStartTimeout();
```

But I get build failure saying that we cannot cast. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project openstack-cloud: Compilation failure
[ERROR] /home/zxiiro/git/jenkins/openstack-cloud-plugin/src/main/java/jenkins/plugins/openstack/compute/JCloudsLauncher.java:[34,52] incompatible types: hudson.slaves.SlaveComputer cannot be converted to jenkins.plugins.openstack.compute.JCloudsSlave

**Comment by olivergondza** [comment]
As this launcher is only used by this plugin, it should be safe to assume what you get in argument is plugin specific subclass. Note that, however, nodes and computers are 2 separate class hierarchies. You should cast it to `JCloudsComputer`.

**Comment by olivergondza** [comment]
I am closing this in favor of https://github.com/jenkinsci/openstack-cloud-plugin/commit/253caa11823cd01a3c81afc750c864d9bb9c6518.

**Comment by zxiiro** [comment]
Thanks, that's certainly a much cleaner patch.

**Pull request closed without merging**
