### PR TITLE
Remove Prototype.js

### LINKED ISSUE #363: Remove usages of Prototype from OpenStack Cloud
See [this blog post](https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/) for details. Prototype will eventually be removed from Jenkins core. To prepare for this transition, this plugin must be migrated away from Prototype. The blog post contains instructions on how to find and eliminate usages of Prototype. In this plugin, the following usages of Prototype have been identified. This may not be an exhaustive list:

```
./plugin/src/main/resources/jenkins/plugins/openstack/compute/JCloudsCloud/computerSet.jelly:23:
new Ajax.Request("${rootURL}/cloud/"+item.value.cloud+"/provision", {
```

CC @olivergondza

### PR DESCRIPTION
**Pull request by basil**
Untested PR. Fixes #363.

### Testing done

None. Please test this, as I am not a user of this plugin.

### CODE REVIEW

**Comment by basil** [comment]
Gentle ping if this could please be released.

**Comment by basil** [comment]
The 2.426 weekly release (Oct 3, 2023) has removed Prototype.

**Comment by olivergondza** [comment]
Thanks, I have spent some time on this, but need to play a bit more to get the release process passing again.

**Comment by olivergondza** [comment]
This was now released as 2.64.

**Pull request merged**
