### PR TITLE
Fixed getPublicAddress to getPublicAddressIpv4 to ensure the selected…

### PR DESCRIPTION
**Pull request by richnou**
… address is IPV4.

Issue came up using OVH openstack which returns IPV6 address as last
address, yielding IPV6 address being returned and Socket connect test
failing.

A unit test could be added based on server descriptor return by OVH provider, but not sure this is very relevant.

### CODE REVIEW

**Comment by richnou** [comment]
I forgot to mention, the code looks for IP version based on the NovaAddress parsed by openstack4j, in such a format:

NovaAddress{address=147.135.218.132, type=fixed, version=4, macaddr=fa:16:3e:9d:02:5c, 
}, NovaAddress{address=2001:41d0:302:1100::2:5658, type=fixed, version=6, macaddr=fa:16:3e:9d:02:5c, 
}

I am not completely sure this is the only format returned by providers, although I assume so.

**Comment by olivergondza** [comment]
I only have an experience with sole IPv4 `NovaAddress`. I can only guess, but I presume there can be IPv6 only setup. I would prefer not to rely on IPv4 to be present at all and they are both just use some of them.

**Comment by richnou** [comment]
Yes, as I mention in code I thought about getting the Address object and check IPV4/6, but then I saw the Socket test and SSH client creation seem to rely on an IPV4 String anywhay...so I thought an IPV6 only setup wouldn't work anyway in the current version, so I forced IPV4 to fix the issue in the actual version.

What's your suggestion, can you merge this and release soon, or do you want to update for IPV4+6 support right away?
Maybe I can also find a way to remove IPV6 from my open stack instance creation.

**Comment by olivergondza** [comment]
Provided this works for you as is, please declare the `JCloudsSlave#getPublicAddressIpv4` as `/*package*/` and `@Restricted(NoExternaluse.class)` so we can change it if we need to tune it.

**Comment by richnou** [comment]
Sorry for the late answer, this is a good for me :) 
Thanks for your feedback

**Pull request merged**
